version: '3.8'

services:
  myportfolio:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase: 