name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
          HostName ${{ secrets.SSH_IP }}
          User ${{ secrets.SSH_USER }}
          IdentityFile ~/.ssh/deploy-key.pem
          StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Debug SSH setup
        run: |
          echo "SSH key file exists: $(ls -la ~/.ssh/deploy-key.pem)"
          echo "SSH config file:"
          cat ~/.ssh/config
          echo "SSH key format check:"
          ssh-keygen -l -f ~/.ssh/deploy-key.pem || echo "Invalid key format"

      - name: Deploy site
        run: ssh my-vps '~/redeploy-site.sh' 